title: LoreSoft.com
author: Paul Welter
description: The collective work of Paul Welter

permalink: /:title
paginate: 5

baseurl: '/'
url: https://www.loresoft.com

disqus: 'loresoft'
analytics: 'UA-575771-2'

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
