baseURL = 'https://loresoft.com/'
languageCode = 'en-us'
title = 'LoreSoft.com'

enableGitInfo = true
enableRobotsTXT = true
disableAliases = false
disableHugoGeneratorInject = true

[params]
  description = "LoreSoft.com - Software Development and Technology Blog featuring .NET, C#, web development, and programming tutorials"
  keywords = "software development, programming, technology, .NET, C#, web development, ASP.NET, Entity Framework, LINQ"
  author = "Paul Welter"
  defaultImage = "/logo/loresoft-logo.png"
  # twitterSite = "@loresoft"
  # twitterCreator = "@yourusername"

[markup]
  [markup.highlight]
    style = 'github'
    lineNos = false

[services]
  [services.disqus]
    shortname = 'loresoft'
  [services.googleAnalytics]
    id = 'G-TTY1SJ9PV9'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
